name: MPS Test

on:
  push:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  builds:
    # name: ${{ matrix.platform.name }}-${{ matrix.build }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Configure
        run:
          cmake -S ${GITHUB_WORKSPACE} -B build
      - name: Build
        run:
          cmake --build build
      - name: Auto Benchmark Cuda
        run: |
          cd multi_process
          #for testing purpose
          ./auto_benchmark.sh -p1 -t1 -c1 -e1 -g1 -r0 -d"/media/chamodya/Backup Plus1/WorkSpace/TRACCC/data"
      - name: Auto Benchmark CPU
        run: |
          cd multi_process
          #for testing purpose
          ./auto_benchmark.sh -p1 -t1 -c1 -e1 -g1 -r1 -d"/media/chamodya/Backup Plus1/WorkSpace/TRACCC/data"
      
